version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
       aliases:
         - post_db
         - comment_db
      back_net:
       aliases:
         - post_db
         - comment_db  
  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - ${PORT}/tcp
    networks:
      - reddit
      - front_net
  post:
    image: ${USERNAME}/post:latest
    networks:
      - reddit
  comment:
    image: ${USERNAME}/comment:latest
    networks:
      - reddit
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - reddit

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - reddit
 
  mongodb-exporter:
    image: ${USERNAME}/mongodb_exporter:latest
    environment:
      - MONGODB_URI='mongodb://mongo_db:27017'
    depends_on:
      - mongo_db
    ports:
      - '9216:9216'
    networks:
      - reddit
      - back_net

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - reddit

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - reddit
  
  alertmanager:
    image: ${USERNAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - reddit      

volumes:
  post_db:
  grafana_data:

networks:
  reddit:
  back_net:
  front_net:
