version: '3'
services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.3.2
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net

  kibana:
    container_name: kibana
    image: kibana:7.3.2
    environment: 
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - back_net
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

networks:
  back_net:
  front_net:
