version: '3'
services:
  fluentd:
    container_name: fluentd
    image: docker_fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.3.2
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net

  kibana:
    container_name: kibana
    image: kibana:7.3.2
    environment: 
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - back_net

networks:
  back_net:
