version: '3.3'
services:
  mongo_db:
    container_name: mongodb
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
       aliases:
         - post_db
         - comment_db
      back_net:
       aliases:
         - post_db
         - comment_db  
  ui:
    container_name: ui
    image: ${USERNAME}/ui:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - '9292:9292'
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - reddit
      - front_net
  post:
    container_name: post
    image: ${USERNAME}/post:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - '5000:5000'
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - reddit
      - front_net
      - back_net
  comment:
    container_name: comment
    image: ${USERNAME}/comment:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - reddit
      - front_net
      - back_net

volumes:
  post_db:

networks:
  reddit:
  back_net:
  front_net:
