{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP response time with 95 percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "UI requests with error",
   "type": "graph",
   "description": "HTTP requests with error status code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count {http_status=~\"^[45].*\"}[5m]) "
    }
   ]
  },
  {
   "title": "UI HTTP requests",
   "type": "graph",
   "description": "All HTTP requests that UI service receives",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count[5m])" }
   ]
  }
 ]
}