FROM alpine:latest
RUN apk update \
    && apk add ruby-full ruby-dev build-base && \ 
    gem install bundler:1.14.6 --no-document

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME
ENV POST_SERVICE_HOST posts
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comments
ENV COMMENT_SERVICE_PORT 9292
CMD ["puma"]
